spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  application:
    name: ms-cards

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    card-emission: card-emission